config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/", to: "welcome#index"
  get "/makes", to: "makes#index", as: "makes"
  get "/makes/new", to: "makes#new"
  post "/makes", to: "makes#create"
  get "/makes/:id", to: "makes#show", as: "make"
  get "/cars", to: "cars#index", as: "cars"
  get "/cars/:id", to: "cars#show", as: "car_show"
  get "/cars/:id/edit", to: "cars#edit", as: "edit_car"
  patch "/cars/:id", to: "cars#update", as: "car_update"
  get "/makes/:make_id/cars", to: "make_cars#index", as: "make_cars"
  get "/makes/:id/edit", to: "makes#edit", as: "edit_make"
  patch "/makes/:id", to: "makes#update", as: "update_make"
  get "/makes/:make_id/cars/new", to: "make_cars#new", as: "new_make_car"
  post "/makes/:make_id/cars", to: "make_cars#create", as: "new_car"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :make
end

app/models/make.rb
class Make < ApplicationRecord
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @makes = Make.all
    @car = Car.find(params[:id])
  end

  def update
    car = Car.find(params[:id])
    car.update(car_params)

    redirect_to car_show_path(car)
  end

  private 
  def car_params
    params.permit(:name, :engine, :new, :make_id)
  end
end

app/controllers/make_cars_controller.rb
class MakeCarsController < ApplicationController
  def index
    @make = Make.find(params[:make_id])
    @cars = @make.cars
  end

  def new
    @make = Make.find(params[:make_id])
    # @car = @make.car.new
  end

  def create
    make = Make.find(params[:make_id])
    car = make.cars.create!(car_params)


    redirect_to "/makes/#{make.id}/cars"
  end

  private
  def car_params
    params.permit(:name, :engine, :new)
  end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  def index
    @makes = Make.all
  end
  
  def new
    @make = Make.new
  end

  def show
    @make = Make.find(params[:id])
  end

  def create
    make = Make.new({
      name: params[:make][:name],
      year: params[:make][:year],
      american: params[:make][:american]
    })

    make.save

    redirect_to "/makes"
  end

  def edit
    @make = Make.find(params[:id])
  end

  def update
    make = Make.find(params[:id])
    make.update(make_params)

    redirect_to make_path(make)
  end

  private
  def make_params
    params.require(:make).permit(:name, :year, :american)
   
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<%= form_with model: @cars, url: car_show_path(@car), method: :patch, data: {turbo:false} do |form| %>
 <%= form.label :name %>
  <%= form.text_field :name%>
  <%= form.label :engine %>
  <%= form.text_field :engine%>
  <%= form.label :new %>
  <%= form.select :new, [true, false] %>
  <%= form.submit "Update #{@car.name}", class: 'button' %>
<% end %>

app/views/cars/index.html.erb
<h1>All Cars</h1>
<% @cars.each do |car| %>
<p><%=link_to car.name, "cars/#{car.id}"%></p>
<% end %> 

app/views/cars/show.html.erb
<h1><%=@car.name%></h1>
<%= link_to "Update #{@car.name}", edit_car_path %>
<ul>
  <li>Number of pistons: <%=@car.engine%></li>
  <li>contition new: <%=@car.new%></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarLot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= link_to "Car Index", cars_path%>
    <%= link_to "Make Index", makes_path %>
    
    <%= yield %>
  </body>
</html>

app/views/make_cars/index.html.erb
<%= link_to "Create Car", new_make_car_path %>
<h1><%="#{@make.name}"%></h1>
<% @cars.each do |car| %>
  <h2>Name: <%= car.name %></h2>
  <p>Number of pistons: <%= car.engine %></p>
  <p>Is it new? <%= car.new %></p>
  <% end %> 
 

app/views/make_cars/new.html.erb
<%= form_with url: "/makes/#{@make.id}/cars", data: {turbo:false} do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, placeholder: "car model" %>
  <%= form.label :engine %>
  <%= form.text_field :engine, placeholder: "number of pistons" %>
  <%= form.label :new %>
  <%= form.select :new, [true, false] %>
  <%= form.submit "Create Car", class: 'button' %>
<% end %>

app/views/makes/edit.html.erb
<%= form_with model: @make, url: update_make_path(@make), method: :patch, data: {turbo:false} do |form| %>
 <%= form.label :name %>
  <%= form.text_field :name%>
  <%= form.label :year %>
  <%= form.text_field :year%>
  <%= form.label :american %>
  <%= form.select :american, [true, false] %>
  <%= form.submit "Update #{@make.name}", class: 'button' %>
<% end %>

app/views/makes/index.html.erb
<h1>Makes</h1>
<%= link_to "Create Make", "/makes/new"  %>
<%@makes.each do |make|%>
<p><h2><%=link_to make.name, "makes/#{make.id}"%></h2> created at: <%= make.created_at %></p>
<%end%>

app/views/makes/new.html.erb
<%= form_with model: Make.new, data: {turbo:false} do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, placeholder: "make name" %>
  <%= form.label :year %>
  <%= form.text_field :year, placeholder: "Year established" %>
  <%= form.label :american %>
  <%= form.select :american, [true, false] %>
  <%= form.submit "Create Make", class: 'button' %>
<% end %>

app/views/makes/show.html.erb
<h1><%=@make.name%></h1>
 <%= link_to "Car_list", make_cars_path(@make) %>
 <%= link_to "Update #{@make.name}", edit_make_path(@make) %>
<ul>
  <li>year: <%=@make.year%></li>
  <li>American made? <%=@make.american%></li>
  <li>Number of cars: <%=@make.cars.count%></li>
  </ul>

app/views/welcome/index.html.erb
<h1>Welcome to the car stuff</h1>
<ul>
  <li><a href=“/makes”>Makes Index</a></li>
  <li><a href=“/cars”>Cars Index</a></li>
</ul>